### ISSUE TITLE
Investigate timer to reset rope positioning cylinder to its open state before robot's rope climb

### ISSUE THREAD

**Issue by jrmihalick** [mr-glt/FRC-2017-Command#4]
Investigate and implement either starting a timer that runs on its own thread or listens/monitors the FRC timer clock which will reset the "rope positioning pneumatic cylinder" to its open state at some time instant (perhaps 1m 45s) during the match.  This will help minimize the chance of the driver accidentally having the cylinder in a closed state as the driver positions the robot to grab the rope.

**Comment by mr-glt** [comment]
I don't think it is possible to poll for the field time, so I am going to write a subsystem and just start a timer when teleop is called.

**Comment by ghost** [comment]
We can also hold a stopwatch if we find that the time is inaccurate.

**Comment by mr-glt** [comment]
There is also a timer that runs on the bottom part of the driver station that you can pace yourself with. The good thing about using command based programing is that the whole thing operates on a timed scheduler, so it should be accurate.
